version: '2'
services:
  mongo_Shard1:
    container_name: mongo_Shard1
    image: mongo
    command: mongos --configdb mongo_ReplicaSet1_Conf/mongo_Config1:27017,mongo_Config2:27017,mongo_Config3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongo_Shard2:
    container_name: mongo_Shard2
    image: mongo
    command: mongos --configdb mongo_ReplicaSet1_Conf/mongo_Config1:27017,mongo_Config2:27017,mongo_Config3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongo_Shard3:
    container_name: mongo_Shard3
    image: mongo
    command: mongos --configdb mongo_ReplicaSet1_Conf/mongo_Config1:27017,mongo_Config2:27017,mongo_Config3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27021:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro